# Generated by Django 5.2.8 on 2026-01-01 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="form",
            name="updated_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="formentry",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="formentry",
            name="updated_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
