# Generated by Django 5.2.8 on 2025-12-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="title",
            field=models.CharField(default=""),
        ),
    ]
