# Generated by Django 5.2.8 on 2026-01-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_form_created_at_alter_form_deadline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(choices=[("VISIT", "visit")], default="VISIT"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.form"
                    ),
                ),
            ],
        ),
    ]
